models:
  - name: mart_customer_segmentation
    description: "A customer view that provides for segmentation"
    columns:
      - name: customer_id
        description: "Unique id of the customer"
      - name: FIRST_NAME
        description: "Customer first name"
      - name: LAST_NAME
        description: "Customer last name"
      - name: EMAIL
        description: "Customer email address"
      - name: last_application_date
        description: "The last data a customer submitted a loan application"
      - name: loan_application_count
        description: "The number of applicaitons a customer has submitted "
      - name: total_loans
        description: "The total number of loans of a customer"
      - name: total_loans_active
        description: "The total number of active loans of a customer"
      - name: total_loans_paid
        description: "The total number of paid loans of a customer"
      - name: last_payment_date
        description: "The date of the last payment of a customer"
      - name: last_payment_type
        description: "The type of payment made of a customer"
      - name: last_payment_amount
        description: "The last payment amount of a customer"
  - name: mart_loan_performance
    description: "The performance of loans"
  - name: mart_loan_metric
    description: "Loan metric split across time slices"
  