version: 2

models:
  - name: dim_customer
    description: "The Customer Dimension"
    

  - name: DIM_APPROVED_LOAN
    description: "The Approved Loan Dimension"
    columns:
      - name: APPROVED_LOAN_SCD2_ID
        description: "The surrogate key of the record"
        tests:
          - unique
          - not_null
      - name: APPROVED_LOAN_ID
        description: "The surrogate key of the table"
        tests:
          - not_null
      - name: APPLICATION_ID
        description: "The Foreign key of the Application table"
      - name: CUSTOMER_ID
        description: "The Foreign key of the Customer table"
      - name: DISBURSEMENT_DATE
        description: "Loan disbursement date"
      - name: MATURITY_DATE
        description: "Loan maturity date"
      - name: APPROVED_LOAN_AMOUNT
        description: "Approved loan amount"
      - name: ANNUAL_INTEREST_RATE
        description: "Annual interest rate"
      - name: SOURCE_APPROVED_LOAN_NUMBER
        description: "The natural key of the table"
        tests:
          - not_null
      - name: LOAN_STATUS
        description: "Loan status (e.g., “Active”, “Paid”, “Defaulted”)"
      - name: VERSION
        description: "The version or iteration of the record"
      - name: IS_CURRENT
        description: "The current version or last version of the record"
      - name: DBT_UPDATED_AT
        description: "The datetime of the update of the  record within the data process"
      - name: DBT_VALID_FROM
        description: "The datetime the record was created or updated to this state"
      - name: DBT_VALID_TO
        description: "The datetime the record was ended being in this state"

  - name: FCT_PAYMENT
    description: "The Loan Payment Fact"
    columns:
      - name: Payment_ID
        description: "The surrogate key of the table"
        tests:
          - not_null
      - name: APPROVED_LOAN_ID
        description: "The Foreign key of the Approved Loan table"
      - name: CUSTOMER_ID
        description: "The Foreign key of the Customer table"
      - name: SOURCE_PAYMENT_NUMBER
        description: "The natural key of the table"
        tests:
          - not_null
      - name: PAYMENT_AMOUNT
        description: "Amount paid (decimal)"
      - name: PAYMENT_DATE
        description: "Date of payment"
      - name: PAYMENT_TYPE
        description: "Type of payment (e.g., “Scheduled”, “Prepayment”)"
